name: serral
description: Fast backEnd server framework provided by Dart, like Koa. Easy add middleware at before request and after request. Easy extend context Type and values.[express][koa][egg]
version: 0.1.14
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart_serral
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  # 包依赖

dev_dependencies:
  # 开发依赖
  mongo_dart: any
  # build_runner: ^1.3
  # build_test: ^0.10.2
