name: serral
description: 只需要提供一个 router 映射表, 即可启动一个 web 服务
version: 0.0.1
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart-time-log
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  # 包依赖

dev_dependencies:
  # 开发依赖
  # build_runner: ^1.3
  # build_test: ^0.10.2
