name: serral
description: Dart tiny web framework, like Koa
version: 0.1.6
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart_serral
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  # 包依赖

dev_dependencies:
  # 开发依赖
  # build_runner: ^1.3
  # build_test: ^0.10.2
