name: serral
description: Dart 轻巧的 Web 框架, Like Koa
version: 0.0.6
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart-serral
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  # 包依赖

dev_dependencies:
  # 开发依赖
  # build_runner: ^1.3
  # build_test: ^0.10.2
